version: '3'
services:
  whatsapp_web_connection:
    build:
      context: ../whatsapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ~/.docker/whatsapp:/data
  ai:
    build:
      context: ../ai
      dockerfile: Dockerfile
    env_file:
      - secrets.env
