name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-wa-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Whatsapp Web Docker image
      run: docker build . --file ai/Dockerfile --tag m2t-wa:$(date +%s)
  build-ai:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the AI Docker image
      run: docker build . --file whatsapp/Dockerfile --tag m2t-ai:$(date +%s)
